apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: romibedi-business-tls
spec:
  secretName: romibedi-business
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: romibedi.business
  dnsNames:
    - romibedi.business
    - www.romibedi.business
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - romibedi.business
          - www.romibedi.business
